services:
  # Serves useful data about a player and its stats.
  api:
    build:
      context: requirements/api
      dockerfile: Dockerfile
    networks:
      - transcendence
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      WSGI_FILE: ${API_WSGI_FILE}
      PORT: ${API_PORT}
    healthcheck:
      test: "wget -O/dev/null -q http://127.0.0.1:${API_PORT}"
      interval: 1s
      retries: 3
      start_period: 1s
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - api:/var/www/html
