services:
  # Serves static content
  web:
    build:
      context: requirements/web
      dockerfile: Dockerfile
    networks:
      - transcendence
    restart: always
    env_file:
      - path: .env
        required: true
    volumes:
      - static:/usr/share/nginx/html
    healthcheck:
      test: "curl http://127.0.0.1/"
      interval: 2s
      retries: 10
      start_period: 5s
